Vagrant.configure("2") do |cf|
  # NFS Server
  cf.vm.define "nfs-server" do |nfs|
    nfs.vm.box = "mkoellges/my-ubuntu"
    nfs.vm.box_version = "20.04"
    nfs.vm.box_check_update = false
    nfs.ssh.username = 'root'
    nfs.ssh.password = 'root'
    nfs.ssh.insert_key = 'true'
    nfs.vm.network "private_network", ip: "10.37.129.103"
    nfs.vm.provider "parallels" do |n|
      n.name = "nfs-server"
      n.memory = 1024
      n.cpus = 1
    end
    nfs.vm.provision "shell",path: "bootstrap_nfs.sh"
  end
end
